### ISSUE TITLE
Timepicker hours and mins are not aligned in a circle

### ISSUE THREAD

**Issue by EL-MOURABITsaber** [mdbootstrap/TW-Elements#1057] opened 2022-06-20 11:15 UTC
I am trying to use any of the date pickers mentioned here : [https://tailwind-elements.com/docs/standard/forms/timepicker/](url).
Unfortunately the hours and mins are displayed inline as you can see here : [https://imgur.com/nab8VcQ](url).
I'm not sure if i followed an installation step incorrectly .
Any help is much appreciated 👍

**Comment by putrafajarh** [comment] 2022-08-04 00:17
I got the same problem, its like the css for timepicker not loaded

**Comment by Voydahn** [comment] 2022-10-13 13:33
Same problem too, the component himself seems like to work, but is not really ... "elegant" having those numbers floating at the top of his clock 

![image](https://user-images.githubusercontent.com/89933320/195611048-bb8f0069-b1b9-46a6-9fb9-af47859f8ecf.png)

**Comment by zeornelas** [comment] 2022-11-09 16:31
I'm having the same problem. 
It seems that adding the following line under the `content` array on the `tailwind.config.js` file fixes it:
`'./node_modules/tw-elements/dist/css/**/*.css',`

**Comment by Voydahn** [comment] 2022-11-09 18:40
> I'm having the same problem. It seems that adding the following line under the `content` array on the `tailwind.config.js` file fixes it: `'./node_modules/tw-elements/dist/css/**/*.css',`

That's work like a charm. Thanks for your help

**Comment by r-jacko** [comment] 2023-01-13 16:45
The problem is currently occurring, the previously proposed solution is good for now. This will be resolved in the next release.

**Comment by smolenski-mikolaj** [comment] 2023-02-20 11:51
Fixed in v1.0.0-beta1

**Closed as completed by smolenski-mikolaj** 2023-02-20 11:51 UTC
Labels: bug, community
